### ISSUE TITLE
Laravel 5.2, "created_at" violates not-null constraint

### ISSUE THREAD

**Issue by manithchhuon** [aginev/activity-log#1]
After saved the data, this error occurred "Not null violation: 7 ERROR: null value in column "created_at" violates not-null constraint".

**Solution :** 
Add constant UPDATED_AT equal to null and change timestamps value to true.

const UPDATED_AT = null;
public $timestamps = true;

**Comment by aginev** [comment]
Works fine for me under
PHP 5.6.3
MySQL 5.6.21
Laravel Framework version 5.2.40
